apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  labels:
    app: cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      containers:
        - name: cloud-gateway
          image: rushiarlekar292/cloud-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9100
      protocol: TCP
  selector:
    app: cloud-gateway
