apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
  labels:
    app: member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member
          image: rushiarlekar292/member-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8092

---
apiVersion: v1
kind: Service
metadata:
  name: member-service-svc
spec:
  ports:
    - port: 80
      targetPort: 8092
      protocol: TCP
  selector:
    app: member